# Generated by Django 5.2.5 on 2026-07-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('Lecture', 'Lecture Hall'), ('Lab', 'Computer Lab'), ('Seminar', 'Seminar Room'), ('Workshop', 'Workshop')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('has_projector', models.BooleanField(default=False)),
                ('has_computers', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['building', 'room_number'],
                'constraints': [models.UniqueConstraint(fields=('building', 'room_number'), name='unique_room')],
            },
        ),
    ]
