# Generated by Django 5.2.5 on 2026-07-23 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('courses', '0001_initial'),
        ('departments', '0001_initial'),
        ('faculty', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_year',
            field=models.CharField(default='2026/2027', help_text='Example: 2026/2027', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab'), ('Tutorial', 'Tutorial'), ('Seminar', 'Seminar')], default='Lecture', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='classrooms.classroom'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables', to='faculty.faculty'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('academic_year', 'semester', 'department', 'day', 'start_time', 'classroom'), name='unique_room_schedule'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('academic_year', 'semester', 'faculty', 'day', 'start_time'), name='unique_faculty_schedule'),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='room_number',
        ),
    ]
